
targets:
  $default:
    builders:
      json_serializable:
        options:
          use_wrappers: false
          any_map: false
          checked: false
          explicit_to_json: true
          generate_to_json_function: true