/// Flutter icons Kipsi_anime
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Kipsi_anime
///      fonts:
///       - asset: fonts/Kipsi_anime.ttf
///
///
///
import 'package:flutter/widgets.dart';

class KipsiAnime {
  KipsiAnime._();

  static const _kFontFam = 'Kipsi_anime';

  static const IconData anilist_icon =
      const IconData(0xe800, fontFamily: _kFontFam);
}
