query AnimeInProgress($userId: Int, $perPage: Int) {
  Anime: Page(perPage: $perPage) {
    mediaList(userId: $userId, type: ANIME, status_in: [CURRENT, REPEATING], sort: UPDATED_TIME_DESC) {
      id
      status
      score
      progress
      progressVolumes
      media {
        id
        type
        status
        format
        episodes
        title {
          userPreferred
        }
        coverImage {
          large
        }
        nextAiringEpisode {
          airingAt
          timeUntilAiring
          episode
        }
      }
    }
  }
}
