query Following(
  $page: Int,
  $types:[ActivityType] = [TEXT, ANIME_LIST, MANGA_LIST]
) {
  Page(page: $page, perPage: 10) {
    pageInfo {
      total
      perPage
      currentPage
      lastPage
      hasNextPage
    }
    activities(
      isFollowing: true
      type_in: $types 
      sort: ID_DESC
    ) {
      __typename
      ... on TextActivity {
        id
        userId
        type
        replyCount
        text
        createdAt
        user {
          id
          name
          donatorTier
          donatorBadge
          avatar {
            large
          }
        }
        likes {
          id
          name
          avatar {
            large
          }
        }
      }
      ... on ListActivity {
        id
        userId
        type
        status
        progress
        replyCount
        createdAt
        user {
          id
          name
          donatorTier
          donatorBadge
          avatar {
            large
          }
        }
        media {
          id
          type
          status
          isAdult
          title {
            userPreferred
          }
          coverImage {
            large
          }
        }
        likes {
          id
          name
          avatar {
            large
          }
        }
      }
    }
  }
}
