query Profile {
  Viewer {
    id
    name
    about
    avatar {
      large
    }
    unreadNotificationCount
    options {
      titleLanguage
      airingNotifications
      displayAdultContent
      profileColor
      notificationOptions {
        type
        enabled
      }
    }
    mediaListOptions {
      scoreFormat
      rowOrder
      animeList {
        customLists
        sectionOrder
        advancedScoring
        advancedScoringEnabled
      }
    }
  }
}
